<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.5</version>
        <relativePath/>
    </parent>

    <groupId>com.agnostic</groupId>
    <artifactId>framework-agnostic-demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>framework-agnostic-demo</name>
    <description>Demo project for Framework Agnostic Design</description>

    <packaging>pom</packaging>

    <properties>
        <java.version>25</java.version>
        <spring-boot-version>4.0.5</spring-boot-version>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <h2.version>2.3.232</h2.version>
        <jakarta.inject-api.version>2.0.1</jakarta.inject-api.version>
        <jakarta.persistence-api.version>3.1.0</jakarta.persistence-api.version>
    </properties>

    <modules>
        <module>business-logic</module>
        <module>spring-boot-deployment</module>
        <module>database-module</module>
    </modules>

</project>